-- Create Job Postings Table
create table public.job_postings (
  id bigint generated by default as identity primary key,
  title text not null,
  location text not null,
  type text not null,
  description text not null,
  apply_url text not null,
  status text default 'active' check (status in ('active', 'inactive', 'filled')),
  deadline timestamptz,
  "order" integer default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Create Team Members Table
create table public.team_members (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null,
  bio text,
  image text,
  "order" integer default 0,
  active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Enable Row Level Security (RLS)
alter table public.job_postings enable row level security;
alter table public.team_members enable row level security;

-- Create Policies (Public Read, Admin Write)
-- Note: For simplicity, we are allowing public read access. 
-- Writing requires service_role key or authenticated user if we implement Supabase Auth fully.
-- For now, we'll allow anonymous public read.

create policy "Enable read access for all users" on public.job_postings
  for select using (true);

create policy "Enable read access for all users" on public.team_members
  for select using (true);

-- Allow insert/update/delete only for service role or authenticated users (if using Supabase Auth)
-- For this "external server" replacement, we might rely on the backend (using service_role key) to do writes.
-- When using the service_role key in the backend, RLS is bypassed, so these policies are mainly for frontend/client access if we had any.
